### ISSUE TITLE
how can I find your paper?

### ISSUE THREAD

**Issue by jmclouds-scut** [duchuyle108/SDN-TMprediction#2]
Hello, author, thank you very much for your willingness to share your detailed work, it helped me a lot. But when I wanted to know more, I couldn't find your paper anyway, which is "An AI-based Traffic Matrix Prediction Solution for Software-Defined Network". Could you tell me how to find this article?

**Comment by duchuyle108** [comment]
Hello. Thank you for being interested in our work. Unfortunately, the paper is not publicly available yet. It would be only published after the conference [ICC2021](https://icc2021.ieee-icc.org/) is held this June. We can not tell the exact date because the process (to  submit all papers to IEEE system) can take several months nor provide anything else.
